### ISSUE TITLE
Doesn't work in Vesktop at all, but works with official Discord

### ISSUE THREAD

**Issue by shvedes** [EnderIce2/rpc-bridge#9]
**Describe the bug**
Title is self-explanatory

**To Reproduce**
1. Open your game with installed bridge.exe
2. Check your Discord activity in Vesktop => nothing
3. Check you Discord activity in Discord official app => activity is shown

**Screenshots**
| Vesktop | Discord |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/04689599-38d0-40e4-b2f5-f0995204f656) | ![image](https://github.com/user-attachments/assets/69d4041a-7bb0-46be-951d-08c1e0218f82) |

**Log File**
```
Running as service
Starting service
Service started
Pipe \\.\pipe\discord-ipc-0(0x98) created
Waiting for pipe connection
```

**Device (please complete the following information):**
 - OS: Tested on both Arch and CachyOS Linux
 - Version: rolling
 Note: CachyOS's ufw (which is enabled by default) is disabled

**Additional context**
- **arRPC is enabled**:
![image](https://github.com/user-attachments/assets/84532609-cb3e-4d15-8e6d-f1d7b58eaaba)
Note: it is actual vesktop app, app name and icon in the title bar is just KDE overrides

- **systemd service is running**:
```
● arrpc.service - arRPC Discord RPC daemon
Loaded: loaded (/usr/lib/systemd/user/arrpc.service; enabled; preset: enabled)
Active: active (running) since Sat 2024-11-16 10:09:47 CET; 5h 4min ago
Invocation: 6192addb8515407790fcdb9a0e7ecf9b
Main PID: 868 (node)
Tasks: 11 (limit: 38270)
Memory: 147.5M (peak: 154M)
CPU: 8min 48.499s
CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/arrpc.service
└─868 node /usr/bin/arrpc

Nov 16 10:54:28 CachyOS arrpc[868]:   code: 'EPIPE',
Nov 16 10:54:28 CachyOS arrpc[868]:   syscall: 'write'
Nov 16 10:54:28 CachyOS arrpc[868]: }
Nov 16 10:54:28 CachyOS arrpc[868]: [arRPC > ipc] socket closed true
Nov 16 11:00:30 CachyOS arrpc[868]: [arRPC > ipc] new connection!
Nov 16 14:25:12 CachyOS arrpc[868]: [arRPC > ipc] new connection!
Nov 16 14:48:43 CachyOS arrpc[868]: [arRPC > ipc] new connection!
Nov 16 14:51:55 CachyOS arrpc[868]: [arRPC > bridge] web connected
Nov 16 14:53:50 CachyOS arrpc[868]: [arRPC > bridge] web disconnected
Nov 16 14:53:58 CachyOS arrpc[868]: [arRPC > bridge] web connected
```

**Comment by Arcitec** [comment]
arRPC is not great at parsing Rich Presence data. Probably arRPC bug!

https://github.com/EnderIce2/rpc-bridge/blob/master/docs/index.md#known-issues

**Comment by EnderIce2** [comment]
@shvedes Based on the screenshots, looks like you are playing [Burnout™ Paradise Remastered](https://store.steampowered.com/app/1238080/Burnout_Paradise_Remastered)?
If so, the game doesn't have [Discord GameSDK](https://discord.com/developers/docs/rich-presence/using-with-the-game-sdk). That's up to the game developer to add it.
This project targets games with this SDK ([more info under Now Playing](https://enderice2.github.io/rpc-bridge/#examples) aka rich presence).

**Comment by shvedes** [comment]
Yes, it is, but despite this, RPC is still shows game's process in disord app, which means that your programm actually works, but again, only with original discord app. 
I will try another game and tell how it's going

**Comment by shvedes** [comment]
Death Stranding (I am sure that this game has RPC support). RPC Still using game process:
| Discord | Vesktop |
| --- | --- | 
| ![image](https://github.com/user-attachments/assets/8745085c-b4c5-4f92-8b7a-881421601ef8) | ![image](https://github.com/user-attachments/assets/8971789c-64e1-48d1-8572-6068b6da1836) |

- - - 
Gof of War (2018). Still the same situation:
| Discord | Vesktop |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/71a6dcca-c3ae-47be-9444-1893316a958a) | ![image](https://github.com/user-attachments/assets/91c9e006-c82e-4e09-857f-d122720d727f) |

- - -

God of War Ragnarok:

| Discord | Vesktop |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/a95751cf-d6a9-4fe2-bab2-94dfb965b9c7) | ![image](https://github.com/user-attachments/assets/edf5475a-96b3-4988-ab4f-76e999492d7e) |

**Comment by shvedes** [comment]
`bridge.exe` can automatically detect `/run/user/$UID/discord-ipc-1`, which is official discord, but can't detect the primary one, which is `discord-ipc-0` taken by vesktop

**Comment by EnderIce2** [comment]
> Death Stranding (I am sure that this game has RPC support). RPC Still using game process:
> Gof of War (2018)
> God of War Ragnarok

I think you are confusing the game detection and RPC (which are not the same).
Official Discord client detects what game are you running (even if it's under Proton/Wine) and shows in the profile, [but it's known that is not showing correctly the names](https://support.discord.com/hc/en-us/community/posts/360071385272-Game-Detection-on-Linux), but you can edit this in settings.

[Vesktop doesn't have this feature.](https://github.com/Vencord/Vesktop/issues/481#issuecomment-2371844196) That's why it's showing only in official Discord client.

Example of rich presence:
![image](https://github.com/user-attachments/assets/70382b4b-1603-4da1-9c58-f3466da56238)

As you can see, we have info such "In a Group" and a button to join. This project makes this to appear on your profile ONLY on games that have this implemented.

**Comment by shvedes** [comment]
Okay, probabbly we are misunderstooding each other.
I don't have the goal to achive buttons, groups, etc in RPC, i just want one thing: display my current game in profile, like windows client does. If i open my game on windows (which is not supports parties and same stuff, just game name and it's icon). 
For example, Death Stranding mentioned above does not have multi-player, so we can't get buttons for this activity (AKA "Ask to Join") and detailed info about game locations, where i currently in. The only thing that works and works well - it's displaying game's name and i'ts icon. Thats what i am trying to achive.

If your project do a slightly different thing, then it's my bad for missunderstanding how this thing works

**Comment by Arcitec** [comment]
> [Vesktop doesn't have this feature.](https://github.com/Vencord/Vesktop/issues/481#issuecomment-2371844196) That's why it's showing only in official Discord client.

Vesktop has this feature. People just don't know what they are doing.

- arRPC uses process scanning and detects games via the same game list as official Discord, and displays the correct names and images for those games.
- arRPC must be running on the host, not a Flatpak.
- This means it works in 2 ways: Either install Vesktop on the host (NOT Flatpak), or install standalone arRPC on the host, disable the built-in arRPC inside Vesktop Flatpak, and enable the Vesktop plugin for talking to arRPC via websockets.

**Comment by Arcitec** [comment]
> Death Stranding (I am sure that this game has RPC support). RPC Still using game process:

Your screenshots are not showing RPC. It's showing Discord's super-shitty process scanner on Linux, which picks up random .exe files and displays them with their basic exe name. If you run Steam games it often shows stuff like wineserver or pressure-vessel as the game name.

So in fact none of your screenshot are showing any RPC anywhere.

Let's go back to basics:

1. arRPC is the ONLY good Process Scanner for Linux, capable of detecting game processes and displaying the correct names.
2. If you use arRPC, it must run on the host (not Flatpak), see my previous comment.
3. Your RPC is not working at all. Are your games running inside a Flatpak app such as Steam Flatpak, Lutris Flatpak, Bottles Flatpak, Heroic Flatpak? If so, you need to use my bridge. There is no other way: https://github.com/EnderIce2/rpc-bridge/issues/8
4. Beware that arRPC's support for Rich Presence statuses coming from games is limited as mentioned here. If you know that a game uses RPC and it's failing in arRPC, report it to arRPC: https://github.com/EnderIce2/rpc-bridge/issues/9#issuecomment-2480670098

**Comment by shvedes** [comment]
> The only thing that works and works well - it's displaying game's name and i'ts icon. Thats what i am trying to achive.

![image](https://github.com/user-attachments/assets/401427f0-5166-4b1f-ad15-8325e1f1aeae)
Screenshot from Windows

**Comment by Arcitec** [comment]
Read my last 2 comments. Every answer is there. All of it.

**Comment by shvedes** [comment]
> Read my last 2 comments. Every answer is there. All of it.

Just have to screenshot it and reboot again. 
No, i don't use flatpaks at all
arRPC is running on host. I've mentioned this in the first message

**Comment by Arcitec** [comment]
Okay good. And you aren't using AppImages or Snaps or any other container formats to run your games, I hope?

Anyway, as for game detection, the easiest way to debug what is happening is to clone the arRPC repo here:

https://github.com/OpenAsar/arRPC

Then run it locally via `npm install` and `node src` on the host.

It will show a terminal explaining each game process that arRPC's scanner is detecting.

Run some Windows games. If their exe filenames are supported by the game list, you will see messages in the arRPC console saying that a game was detected.

If you are curious about the game list and what `.exe` files it scans for, it's somewhere inside their repo in a .json file. The list comes directly from Discord themselves.

**Comment by shvedes** [comment]
Will try this now. Thanks

**Comment by Arcitec** [comment]
Good luck. And remember, this only deals with game detection for non-RPC games. If you want Rich Presence, you need to use `rpc-bridge` inside wine, which will connect the Windows RPC socket to the UNIX RPC socket. So that Windows games Rich Presence messages are being bridged to Linux.

Then close all other discord clients completely (to ensure that `$XDG_RUNTIME_DIR/discord-ipc-*` files DO NOT EXIST anymore)?. Then start arRPC standalone and ensure you get the `discord-ipc-0` socket.

Then run a Wine game that uses `rpc-bridge`.

Watch the arRPC console to see if it receives the Rich Presence message.

Then you have to hope that arRPC supports the incoming RPC Message, because as mentioned, they have some problems parsing some of the messages that games send out. :/

**Comment by Arcitec** [comment]
I also saw a big problem in your Vesktop config. You have disabled arRPC. :)

**Comment by shvedes** [comment]
> I also saw a big problem in your Vesktop config. You have disabled arRPC. :)

Huh? How did you know that?

**Comment by Arcitec** [comment]
This is NOT arRPC:

![image](https://github.com/user-attachments/assets/1ac748ce-588e-4c9c-89fa-a5c155e3b638)

THIS is arRPC:

![image](https://github.com/user-attachments/assets/051ac4a6-b946-4175-a824-715fde519fec)

**Comment by shvedes** [comment]
> This is NOT arRPC:

![image](https://github.com/user-attachments/assets/283cf774-10f6-4f0f-9e71-63a12b835521)
It's enabled. 


![image](https://github.com/user-attachments/assets/d742fe09-f509-4248-8883-5060fa36e7e6)

**Comment by Arcitec** [comment]
> It's enabled.

Read carefully. ;) https://github.com/EnderIce2/rpc-bridge/issues/9#issuecomment-2480830422

Disable that plugin which you showed in your 1st post: https://github.com/EnderIce2/rpc-bridge/issues/9#issue-2664425646

**Comment by shvedes** [comment]
Already did a while ago. I only have the vesktop's one

![image](https://github.com/user-attachments/assets/ee5f43b9-504e-4ac7-bf61-5b88308cf35d)
![image](https://github.com/user-attachments/assets/73c377ed-75d5-4796-8b01-fc6ac053cef0)



> you must look at arRPC's game list

Will do now!

**Comment by Arcitec** [comment]
https://raw.githubusercontent.com/OpenAsar/arrpc/refs/heads/main/src/process/detectable.json

`{"executables": [{"is_launcher": false, "name": "horizon zero dawn/horizonzerodawn.exe", "os": "win32"}], "hook": true, "id": "1124351698740195439", "name": "Horizon Zero Dawn"}`

This means arRPC will look for that filename: `"horizon zero dawn/horizonzerodawn.exe"`

Do `ps aux | grep -i zerodawn`.

I know there's been some situations where people say arRPC process scanner cannot detect the true path to a game and fails to detect it. Personally I never saw any issues.

**Comment by Arcitec** [comment]
Can confirm, arRPC is detecting Horizon Zero Dawn:

![image](https://github.com/user-attachments/assets/913d32f6-38ea-4fa8-963b-9c1fe6adfa63)

**Comment by Arcitec** [comment]
And native Vesktop's built-in arRPC is also detecting it:

![image](https://github.com/user-attachments/assets/4fa647f1-f150-4705-8232-4c7613bfd748)

**Comment by shvedes** [comment]
Weird af. Sorry for my language
Will try one more time. Thank you for trying to help!

**Comment by shvedes** [comment]
Ok, lets start from scratch.
I have vesktop, which is not flatpak version.
I have games, which is not in any sandbox (pure system wine staging 9.21)
For the test i will use God of War (2018). I checked this game in the arrpc database, and it exist there (Horizon Zero Dawn Remastered is not shown there).
I have system-wide arrpc installed from AUR (git version), version 3.5.0. The cloned one is the same version as system's, so i will use the AUR ver.
In vesktop settings RichPresence setting is ON and arrpc plugin in plugins section is OFF.
Bridge is installed in game's wine prefix, so no problems with it.

What i should to do, step by step?
- Kill all existing discord / vesktop processes and make sure that no one `discord-ipc-* is running
- Then start arrpc, wait for `discord-ipc-0` creation, and then launch my game
- Then go to arrpc logs and check if the game was detected
- If so, kill arrpc, kill the game and launch vesktop with it's own arrpc implementation then launch the game again and check if Rich Presence is working

Right?

**Comment by Arcitec** [comment]
Okay that means your Vesktop is:

- Running on native host, meaning the process scanner has permission to check all running games. Good.
- Using built-in arRPC (Rich Presence (aka internal arRPC) on, WebRichPresence (aka external arRPC) off). Good.

Your games are:

- Running via Wine Staging, not Steam/Proton, apparently.
- You mention that the games are not in a sandbox. So I'll just mention that arRPC's process detection doesn't care if the games are sandboxed or not, it finds the `.exe` processes either way.

So that means it's able to scan all your game processes, for sure.

To verify why it's not finding your game, you need to do two things:

- Check what the exact path for the game is in https://raw.githubusercontent.com/OpenAsar/arrpc/refs/heads/main/src/process/detectable.json
- Run `ps aux | grep -i <some part of that exe name>` and look at the results to see if your own game exe matches that (case insensitive) name.

If you know some programming you might also want to open `src/process/` in arRPC source code and mess around with some extra print statements to see what processes it's finding and rejecting, but you shouldn't have to do any of that.

My guess right now is one of two things:

- Either arRPC doesn't find the Windows process path correctly when running in plain Wine instead of a wrapper such as Steam, Bottles, etc.
- Or perhaps your game is a different edition with slightly different filename.

**Comment by shvedes** [comment]
> * Most EXEs in Discord's list are paths like "folder name/exe name.exe".

![image](https://github.com/user-attachments/assets/7263b5ee-654b-4654-a0b4-b9ae5a73f1dd)

**Well**, i guess that was a problem, maybe.
Will rename my game folder now and try again

**Comment by Arcitec** [comment]
I personally just verified a Bottles game too, running it with wine-ge-proton8-26:

- It runs with this path: `drive_c/Program Files/ELDEN RING Deluxe/ELDEN RING/Game/eldenring.exe`
- Detectable scans for that path: `{"aliases": ["ELDEN RING"], "executables": [{"is_launcher": false, "name": "game/eldenring.exe", "os": "win32"}], "hook": true, "id": "946609449680908348", "name": "ELDEN RING", "overlay": true}`

![image](https://github.com/user-attachments/assets/a29f1b19-d1b6-43f2-8144-b4ddaed33f89)

So at least we know for sure that Steam and Bottles environment EXE names are understandable by arRPC.

**Comment by shvedes** [comment]
![image](https://github.com/user-attachments/assets/886838db-9f7b-4138-b48c-29a802b0ae0c)
I have no words...
This was insanely simple and dumb at the same time!
**THANK YOU** for the help, i appreciate it!!!

**Comment by Arcitec** [comment]
@shvedes :heart: Okay cool so that also taught me (verified) that the folder name also matters. Useful to know. Also taught me that arRPC process scanner can find games in plain Wine too, doesn't need Steam/Bottles environments. :)

So... now you can uninstall arRPC on the host and rely completely on Vesktop's built-in scanner. Unless you wanna use standalone arRPC for some easier debugging another time.

Vesktop built-in arRPC is nice because it's starting and stopping internally every time Vesktop starts. No need for a separate process.

---

For the second issue: Rich Presence, where the game tells Discord "Hey they are playing XYZ game and they are currently in Lobby and Cooking Apples", is being handled by `rpc-bridge`, which sends that data from Wine to Linux.

That Rich Presence feature exists in arRPC, but it seems like many games send data in a way that arRPC doesn't understand, but the official Discord client apparently works. That's a bug with arRPC.

If you run a game that Rich Presence doesn't work with, then I recommend reading the discussion in https://github.com/EnderIce2/rpc-bridge/issues/4#issuecomment-2143549407 and somewhere there's some method to debug what error arRPC is giving about the incoming game status data. Then report it to https://github.com/OpenAsar/arRPC.

---

And lastly, if you ever run any software in a Flatpak, remember that you need this bridge between Flatpak socket and Native socket: https://github.com/Arcitec/discord-flatpak-rpc-bridge

Have fun with your gaming! :)

**Comment by shvedes** [comment]
***Thank you again!!!*** :heart:
